export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  VERIFY_EMAIL: '/verify-email',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  AUTH_ERROR: '/auth-error',
  DASHBOARD: '/dashboard',
  ADMIN: '/admin',
  ADMIN_REPORTS: '/admin/reports',
  ADMIN_LISTINGS: '/admin/listings',
  ADMIN_MESSAGES: '/admin/messages',
  ADMIN_USERS: '/admin/users',
  ADMIN_STRUCTURE: '/admin/structure',
  MY_LISTINGS: '/dashboard/my-listings',
  FAVORITES: '/dashboard/favorites',
  MESSAGES: '/dashboard/messages',
  OFFERS: '/dashboard/offers',
  PROFILE: '/dashboard/profile',
  SETTINGS: '/dashboard/settings',
  ADD_LISTING: '/dashboard/add-listing',
  BROWSE: '/browse',
  SELLERS: '/sellers',
} as const;
